name: dramalist
description: "MyDramaList Scrapper"
version: 0.0.1

environment:
  sdk: ^3.7.0-154.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
  html:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
